import type { FailurePattern } from "../types/failure-pattern.js";

export const FAILURE_PATTERN_SEEDS: FailurePattern[] = [
  {
    pattern_id: "fp-001",
    name: "Missing empty state on list component",
    description: "List or table component renders blank or errors when no data exists",
    failure_type: "ui_state_failure",
    root_cause_category: "spec_gap",
    affected_stages: ["build_execution", "validation"],
    severity_range: { min: "medium", max: "high" },
    frequency: 0,
    tags: ["ui", "empty-state", "list", "table"],
  },
  {
    pattern_id: "fp-002",
    name: "Clerk auth middleware not protecting API routes",
    description: "API routes accessible without authentication due to missing middleware config",
    failure_type: "permission_failure",
    root_cause_category: "builder_regression",
    affected_stages: ["validation", "pr_check"],
    severity_range: { min: "critical", max: "critical" },
    frequency: 0,
    tags: ["auth", "clerk", "middleware", "security"],
  },
  {
    pattern_id: "fp-003",
    name: "Convex query missing orgId filter",
    description: "Multi-tenant query returns data across organizations due to missing orgId filter",
    failure_type: "permission_failure",
    root_cause_category: "spec_gap",
    affected_stages: ["validation"],
    severity_range: { min: "critical", max: "critical" },
    frequency: 0,
    tags: ["convex", "tenancy", "orgId", "security"],
  },
  {
    pattern_id: "fp-004",
    name: "Offline state not handled for real-time subscription",
    description: "Real-time data subscription shows stale data or crashes when connection drops instead of showing offline indicator",
    failure_type: "offline_state_gap",
    root_cause_category: "spec_gap",
    affected_stages: ["build_execution", "validation"],
    severity_range: { min: "medium", max: "high" },
    frequency: 0,
    tags: ["offline", "real-time", "subscription", "convex"],
  },
  {
    pattern_id: "fp-005",
    name: "Destructive action missing confirmation dialog",
    description: "Delete, archive, or other destructive actions execute immediately without user confirmation step",
    failure_type: "ui_state_failure",
    root_cause_category: "spec_gap",
    affected_stages: ["build_execution", "validation"],
    severity_range: { min: "high", max: "critical" },
    frequency: 0,
    tags: ["ui", "confirmation", "destructive-action", "ux"],
  },
  {
    pattern_id: "fp-006",
    name: "Form submission without Zod validation",
    description: "Form data sent to backend without schema validation, allowing malformed or dangerous input through",
    failure_type: "type_error",
    root_cause_category: "validator_miss",
    affected_stages: ["build_execution", "validation"],
    severity_range: { min: "high", max: "critical" },
    frequency: 0,
    tags: ["form", "zod", "validation", "input"],
  },
  {
    pattern_id: "fp-007",
    name: "Stripe webhook missing HMAC signature validation",
    description: "Webhook endpoint processes Stripe events without verifying the signature, allowing forged events",
    failure_type: "api_integration_failure",
    root_cause_category: "integration_assumption",
    affected_stages: ["validation", "pr_check"],
    severity_range: { min: "critical", max: "critical" },
    frequency: 0,
    tags: ["stripe", "webhook", "hmac", "security", "payment"],
  },
  {
    pattern_id: "fp-008",
    name: "Missing loading skeleton on data fetch",
    description: "Component shows nothing or flashes content while data is loading instead of displaying a loading skeleton",
    failure_type: "ui_state_failure",
    root_cause_category: "spec_gap",
    affected_stages: ["build_execution"],
    severity_range: { min: "low", max: "medium" },
    frequency: 0,
    tags: ["ui", "loading", "skeleton", "ux"],
  },
  {
    pattern_id: "fp-009",
    name: "XState transition not guarded for unauthorized role",
    description: "State machine allows transitions that should be restricted by user role, bypassing permission checks",
    failure_type: "permission_failure",
    root_cause_category: "rule_missing",
    affected_stages: ["validation"],
    severity_range: { min: "high", max: "critical" },
    frequency: 0,
    tags: ["xstate", "guard", "role", "permission", "state-machine"],
  },
  {
    pattern_id: "fp-010",
    name: "Convex mutation missing audit log call",
    description: "Data-modifying mutation does not write to the audit log, breaking compliance and traceability requirements",
    failure_type: "workflow_gap",
    root_cause_category: "spec_gap",
    affected_stages: ["validation"],
    severity_range: { min: "medium", max: "high" },
    frequency: 0,
    tags: ["convex", "mutation", "audit-log", "compliance"],
  },
  {
    pattern_id: "fp-011",
    name: "Error boundary not catching async errors",
    description: "React error boundary only catches synchronous render errors; async errors in useEffect or event handlers crash the app",
    failure_type: "fallback_gap",
    root_cause_category: "builder_regression",
    affected_stages: ["build_execution", "validation"],
    severity_range: { min: "medium", max: "high" },
    frequency: 0,
    tags: ["react", "error-boundary", "async", "crash"],
  },
  {
    pattern_id: "fp-012",
    name: "Responsive layout breaks at tablet breakpoint",
    description: "Layout overlaps, overflows, or becomes unusable between 768px and 1024px viewport width",
    failure_type: "ui_state_failure",
    root_cause_category: "spec_gap",
    affected_stages: ["build_execution", "validation"],
    severity_range: { min: "medium", max: "high" },
    frequency: 0,
    tags: ["responsive", "tablet", "breakpoint", "layout", "css"],
  },
  {
    pattern_id: "fp-013",
    name: "PWA service worker caching stale data",
    description: "Service worker serves outdated cached responses after deployment, showing users stale content or broken features",
    failure_type: "deployment_failure",
    root_cause_category: "integration_assumption",
    affected_stages: ["deployment", "validation"],
    severity_range: { min: "high", max: "critical" },
    frequency: 0,
    tags: ["pwa", "service-worker", "cache", "deployment", "stale"],
  },
  {
    pattern_id: "fp-014",
    name: "Notification trigger missing recipient filter",
    description: "Notification sent to all users instead of just the intended recipient due to missing filter on the trigger query",
    failure_type: "permission_failure",
    root_cause_category: "spec_gap",
    affected_stages: ["validation"],
    severity_range: { min: "high", max: "critical" },
    frequency: 0,
    tags: ["notification", "recipient", "filter", "privacy"],
  },
  {
    pattern_id: "fp-015",
    name: "API endpoint returning 500 instead of typed error",
    description: "Server endpoint throws unhandled exception returning generic 500 instead of a structured error response with code and message",
    failure_type: "api_integration_failure",
    root_cause_category: "builder_regression",
    affected_stages: ["build_execution", "validation"],
    severity_range: { min: "medium", max: "high" },
    frequency: 0,
    tags: ["api", "error-handling", "500", "typed-error"],
  },
  {
    pattern_id: "fp-016",
    name: "Feature dependency built out of order",
    description: "A feature that depends on another is built first, causing import errors or missing runtime dependencies",
    failure_type: "missing_dependency",
    root_cause_category: "catalog_mismatch",
    affected_stages: ["build_execution"],
    severity_range: { min: "high", max: "critical" },
    frequency: 0,
    tags: ["dependency", "order", "build", "orchestration"],
  },
  {
    pattern_id: "fp-017",
    name: "Bridge write scope too narrow for required files",
    description: "Bridge configuration restricts file writes to a subset that does not include all files the builder needs to modify",
    failure_type: "workflow_gap",
    root_cause_category: "bridge_gap",
    affected_stages: ["build_execution"],
    severity_range: { min: "high", max: "high" },
    frequency: 0,
    tags: ["bridge", "scope", "write-permission", "file-access"],
  },
  {
    pattern_id: "fp-018",
    name: "Reuse asset version mismatch",
    description: "Catalog references a reuse asset at a version that is incompatible with the current project dependencies",
    failure_type: "missing_dependency",
    root_cause_category: "catalog_mismatch",
    affected_stages: ["build_execution"],
    severity_range: { min: "medium", max: "high" },
    frequency: 0,
    tags: ["reuse", "version", "catalog", "compatibility"],
  },
  {
    pattern_id: "fp-019",
    name: "Test fixture not matching production schema",
    description: "Test uses hardcoded fixtures that do not match the current Convex schema, causing false passes or type errors",
    failure_type: "test_failure",
    root_cause_category: "builder_regression",
    affected_stages: ["validation"],
    severity_range: { min: "medium", max: "high" },
    frequency: 0,
    tags: ["test", "fixture", "schema", "convex", "drift"],
  },
  {
    pattern_id: "fp-020",
    name: "Deploy fails due to missing environment variable",
    description: "Production or staging deployment fails because a required environment variable is not set in the deployment target",
    failure_type: "deployment_failure",
    root_cause_category: "environment_issue",
    affected_stages: ["deployment"],
    severity_range: { min: "high", max: "critical" },
    frequency: 0,
    tags: ["deploy", "env-var", "environment", "config"],
  },
  {
    pattern_id: "fp-021",
    name: "Optimistic update not rolling back on mutation failure",
    description: "UI applies optimistic update but does not revert when the server mutation fails, leaving UI in an inconsistent state",
    failure_type: "ui_state_failure",
    root_cause_category: "builder_regression",
    affected_stages: ["build_execution", "validation"],
    severity_range: { min: "high", max: "high" },
    frequency: 0,
    tags: ["optimistic-update", "rollback", "mutation", "convex", "ui"],
  },
  {
    pattern_id: "fp-022",
    name: "Role guard checking wrong permission key",
    description: "Authorization guard references an incorrect or outdated permission key, allowing or denying access incorrectly",
    failure_type: "permission_failure",
    root_cause_category: "rule_missing",
    affected_stages: ["validation"],
    severity_range: { min: "critical", max: "critical" },
    frequency: 0,
    tags: ["role", "guard", "permission", "auth", "key-mismatch"],
  },
  {
    pattern_id: "fp-023",
    name: "Date timezone handling inconsistent",
    description: "Dates displayed or stored without consistent timezone handling, causing off-by-one-day errors or wrong times across regions",
    failure_type: "type_error",
    root_cause_category: "spec_gap",
    affected_stages: ["build_execution", "validation"],
    severity_range: { min: "medium", max: "high" },
    frequency: 0,
    tags: ["date", "timezone", "utc", "locale", "off-by-one"],
  },
  {
    pattern_id: "fp-024",
    name: "File upload exceeding Convex storage limits",
    description: "File upload handler does not check file size before upload, causing Convex storage limit errors at runtime",
    failure_type: "api_integration_failure",
    root_cause_category: "integration_assumption",
    affected_stages: ["build_execution", "validation"],
    severity_range: { min: "medium", max: "high" },
    frequency: 0,
    tags: ["file-upload", "convex", "storage", "limit", "size-check"],
  },
  {
    pattern_id: "fp-025",
    name: "Workflow step missing error transition",
    description: "XState or workflow step has no error transition defined, causing the workflow to hang or crash on unexpected failures",
    failure_type: "workflow_gap",
    root_cause_category: "spec_gap",
    affected_stages: ["build_execution", "validation"],
    severity_range: { min: "high", max: "critical" },
    frequency: 0,
    tags: ["workflow", "xstate", "error-transition", "state-machine", "hang"],
  },
];
