import type { FixPattern } from "../types/fix-pattern.js";

export const FIX_PATTERN_SEEDS: FixPattern[] = [
  {
    pattern_id: "fix-001",
    name: "Add empty state component to list views",
    description: "Wrap list/table in a conditional that renders an EmptyState component when data array is empty",
    target_failure_patterns: ["fp-001"],
    resolution_action: "update_spec",
    resolution_template: "Add: if (items.length === 0) return <EmptyState icon={...} title='No items yet' description='...' />; before the list render.",
    success_rate: 0.95,
    times_applied: 8,
  },
  {
    pattern_id: "fix-002",
    name: "Add Clerk middleware to unprotected API routes",
    description: "Apply clerkMiddleware() or auth().protect() to API route handlers missing authentication",
    target_failure_patterns: ["fp-002"],
    resolution_action: "patch_bridge",
    resolution_template: "Wrap route handler with clerkMiddleware() in middleware.ts, or add auth().protect() at the top of each API route handler.",
    success_rate: 0.92,
    times_applied: 5,
  },
  {
    pattern_id: "fix-003",
    name: "Add orgId filter to Convex queries",
    description: "Add .filter(q => q.eq(q.field('orgId'), orgId)) to multi-tenant Convex queries",
    target_failure_patterns: ["fp-003", "fp-014"],
    resolution_action: "add_rule",
    resolution_template: "Add orgId argument to query args schema, extract from auth context, and add .filter(q => q.eq(q.field('orgId'), args.orgId)) to all collection queries.",
    success_rate: 0.90,
    times_applied: 6,
  },
  {
    pattern_id: "fix-004",
    name: "Add offline detection and fallback UI",
    description: "Implement useOnlineStatus hook and wrap real-time components with offline fallback",
    target_failure_patterns: ["fp-004"],
    resolution_action: "add_offline_state",
    resolution_template: "Create useOnlineStatus() hook using navigator.onLine + event listeners. Wrap subscription components: if (!online) return <OfflineBanner lastSyncedAt={...} />.",
    success_rate: 0.85,
    times_applied: 3,
  },
  {
    pattern_id: "fix-005",
    name: "Add confirmation dialog for destructive actions",
    description: "Wrap destructive action handlers with a confirmation dialog before executing",
    target_failure_patterns: ["fp-005"],
    resolution_action: "update_spec",
    resolution_template: "Replace direct onClick={handleDelete} with onClick={() => setShowConfirm(true)}, render <ConfirmDialog onConfirm={handleDelete} title='Are you sure?' description='This action cannot be undone.' />.",
    success_rate: 0.98,
    times_applied: 12,
  },
  {
    pattern_id: "fix-006",
    name: "Add Zod schema validation to form submission",
    description: "Define a Zod schema for form data and validate before submission",
    target_failure_patterns: ["fp-006"],
    resolution_action: "add_rule",
    resolution_template: "Define const formSchema = z.object({...}); use zodResolver(formSchema) with react-hook-form, or manually validate with formSchema.safeParse(data) before submit.",
    success_rate: 0.93,
    times_applied: 9,
  },
  {
    pattern_id: "fix-007",
    name: "Add Stripe webhook signature verification",
    description: "Verify Stripe webhook HMAC signature before processing events",
    target_failure_patterns: ["fp-007"],
    resolution_action: "add_rule",
    resolution_template: "Add stripe.webhooks.constructEvent(body, sig, endpointSecret) at the top of the webhook handler. Return 400 if verification fails.",
    success_rate: 0.97,
    times_applied: 4,
  },
  {
    pattern_id: "fix-008",
    name: "Add loading skeleton to data-fetching components",
    description: "Show a skeleton loader while data is being fetched",
    target_failure_patterns: ["fp-008"],
    resolution_action: "update_spec",
    resolution_template: "Add: if (data === undefined) return <Skeleton className='h-[200px] w-full' />; at the top of components using useQuery.",
    success_rate: 0.96,
    times_applied: 15,
  },
  {
    pattern_id: "fix-009",
    name: "Add role guard to XState transitions",
    description: "Add guard conditions checking user role before allowing state transitions",
    target_failure_patterns: ["fp-009", "fp-022"],
    resolution_action: "add_rule",
    resolution_template: "Add guard: ({ context }) => context.userRole === 'admin' || context.userPermissions.includes('required_permission') to restricted transitions in the state machine definition.",
    success_rate: 0.88,
    times_applied: 4,
  },
  {
    pattern_id: "fix-010",
    name: "Add error transition to workflow steps",
    description: "Add onError transition to XState states that can fail",
    target_failure_patterns: ["fp-025"],
    resolution_action: "update_spec",
    resolution_template: "Add onError: { target: 'errorState', actions: 'logError' } to each invoke or async state in the machine. Define errorState with retry and abort transitions.",
    success_rate: 0.90,
    times_applied: 5,
  },
  {
    pattern_id: "fix-011",
    name: "Add optimistic update rollback handler",
    description: "Implement rollback logic when server mutation fails after optimistic UI update",
    target_failure_patterns: ["fp-021"],
    resolution_action: "add_fallback",
    resolution_template: "Store pre-mutation state before optimistic update. In the mutation's onError callback, restore the previous state and show a toast: 'Action failed, changes reverted.'",
    success_rate: 0.82,
    times_applied: 3,
  },
  {
    pattern_id: "fix-012",
    name: "Fix dependency build order in orchestrator",
    description: "Reorder feature builds to respect dependency graph",
    target_failure_patterns: ["fp-016"],
    resolution_action: "narrow_scope",
    resolution_template: "Topologically sort features by their dependency edges before scheduling builds. Block downstream features until all upstream dependencies report success.",
    success_rate: 0.87,
    times_applied: 4,
  },
  {
    pattern_id: "fix-013",
    name: "Widen bridge write scope for builder",
    description: "Expand the bridge file-write scope to include all directories the builder needs to modify",
    target_failure_patterns: ["fp-017"],
    resolution_action: "patch_bridge",
    resolution_template: "Update bridge config writeScope array to include the missing directories. Verify with a dry-run that all required file paths are within the new scope.",
    success_rate: 0.91,
    times_applied: 6,
  },
  {
    pattern_id: "fix-014",
    name: "Add environment variable validation on startup",
    description: "Validate all required environment variables at app startup before any handlers execute",
    target_failure_patterns: ["fp-020"],
    resolution_action: "add_rule",
    resolution_template: "Create envSchema = z.object({ DATABASE_URL: z.string(), ... }); call envSchema.parse(process.env) at the top of the entry file. Fail fast with a clear message listing missing vars.",
    success_rate: 0.94,
    times_applied: 7,
  },
  {
    pattern_id: "fix-015",
    name: "Add file size validation before upload",
    description: "Check file size against limits before initiating the upload to Convex storage",
    target_failure_patterns: ["fp-024"],
    resolution_action: "add_rule",
    resolution_template: "Add: if (file.size > MAX_FILE_SIZE) { toast.error(`File too large. Max size: ${formatBytes(MAX_FILE_SIZE)}`); return; } before calling storage.generateUploadUrl().",
    success_rate: 0.96,
    times_applied: 5,
  },
];
