import type { PreventionRule } from "../types/prevention-rule.js";

export const PREVENTION_RULE_SEEDS: PreventionRule[] = [
  {
    rule_id: "pr-001",
    name: "Require orgId filter on all Convex queries",
    description: "At spec review time, verify that every Convex query touching tenant-scoped data includes an orgId filter argument and applies it in the query filter chain",
    target_failure_patterns: ["fp-003", "fp-014"],
    gate: "gate_1",
    check_logic: "Scan query function signatures for args containing orgId. For each query on a tenant-scoped table, verify .filter includes q.eq(q.field('orgId'), args.orgId). Flag any tenant query missing the filter.",
    added_after_incident: "inc-003",
  },
  {
    rule_id: "pr-002",
    name: "Require auth middleware on all API routes",
    description: "At bridge review time, verify that middleware.ts covers all /api/* routes with clerkMiddleware() or explicit auth checks",
    target_failure_patterns: ["fp-002"],
    gate: "gate_2",
    check_logic: "Parse middleware.ts matcher config. Verify all /api/* paths are covered. Cross-reference with the route file list in app/api/**. Flag any route not matched by the middleware.",
    added_after_incident: "inc-002",
  },
  {
    rule_id: "pr-003",
    name: "Require empty state for all list/table components",
    description: "At spec review time, verify that every component rendering a list or table has a defined empty state",
    target_failure_patterns: ["fp-001"],
    gate: "gate_1",
    check_logic: "For each component spec that renders an array of items, check that the spec includes an empty state definition. Flag components where data.length === 0 case is not handled.",
  },
  {
    rule_id: "pr-004",
    name: "Require confirmation dialog for destructive actions",
    description: "At spec review time, verify that delete, archive, and other destructive actions include a confirmation step",
    target_failure_patterns: ["fp-005"],
    gate: "gate_1",
    check_logic: "Identify all mutation calls tagged as destructive (delete, remove, archive, purge). Verify each has a corresponding confirmation dialog in the UI spec. Flag direct-execution destructive actions.",
  },
  {
    rule_id: "pr-005",
    name: "Require Zod validation on all form submissions",
    description: "At build review time, verify that all form components use Zod schema validation before submitting data",
    target_failure_patterns: ["fp-006"],
    gate: "gate_3",
    check_logic: "Scan form components for onSubmit handlers. Verify each uses zodResolver or explicit safeParse before calling a mutation. Flag forms that pass raw FormData or unvalidated objects to mutations.",
  },
  {
    rule_id: "pr-006",
    name: "Require webhook signature verification",
    description: "At build review time, verify that all webhook endpoints verify request signatures before processing",
    target_failure_patterns: ["fp-007"],
    gate: "gate_3",
    check_logic: "Identify all webhook handler files (*/webhook*, */hook*). Verify each calls the provider's signature verification method (e.g., stripe.webhooks.constructEvent). Flag handlers that process the body without verification.",
  },
  {
    rule_id: "pr-007",
    name: "Require environment variable schema validation",
    description: "At build review time, verify that the app entry point validates all required environment variables at startup",
    target_failure_patterns: ["fp-020"],
    gate: "gate_3",
    check_logic: "Check that the main entry file or a dedicated env.ts imports a Zod schema and calls .parse(process.env). Cross-reference with .env.example to ensure all documented vars are in the schema. Flag missing vars.",
  },
  {
    rule_id: "pr-008",
    name: "Require error transitions on all async workflow states",
    description: "At spec review time, verify that every XState invoke or async state has an onError transition defined",
    target_failure_patterns: ["fp-025"],
    gate: "gate_1",
    check_logic: "Parse state machine definitions. For each state with invoke or async service, verify onError is defined with a target state. Flag states where errors would cause the machine to halt.",
  },
  {
    rule_id: "pr-009",
    name: "Require dependency order validation before build",
    description: "At orchestration time, verify that the feature build order respects the dependency graph with no forward references",
    target_failure_patterns: ["fp-016"],
    gate: "gate_0",
    check_logic: "Topologically sort the feature dependency graph. Compare with the proposed build order. Flag any feature scheduled before its dependencies. Block build if cycle detected.",
  },
  {
    rule_id: "pr-010",
    name: "Require loading and error states for data-fetching components",
    description: "At spec review time, verify that every component using useQuery or data fetching has loading and error state handling",
    target_failure_patterns: ["fp-008", "fp-011", "fp-015"],
    gate: "gate_1",
    check_logic: "For each component spec using data fetching, verify it defines: (1) loading state with skeleton/spinner, (2) error state with message and retry, (3) success state with data render. Flag components missing any of these three states.",
  },
];
