import type { ValidatorHeuristic } from "../types/validator-heuristic.js";

export const VALIDATOR_HEURISTIC_SEEDS: ValidatorHeuristic[] = [
  {
    heuristic_id: "vh-001",
    name: "Detect unprotected API routes",
    description: "Scan route files for handlers that do not invoke auth middleware or auth().protect()",
    target_failure_patterns: ["fp-002"],
    validator_tier: "tier_a",
    detection_logic: "List all files matching app/api/**/route.ts. For each, check if the file imports and calls clerkMiddleware, auth().protect(), or equivalent. Also verify middleware.ts matcher covers the route path. Report unprotected routes as critical findings.",
    false_positive_rate: 0.05,
  },
  {
    heuristic_id: "vh-002",
    name: "Detect missing orgId filter in Convex queries",
    description: "Scan Convex query functions for tenant-scoped tables missing orgId filter",
    target_failure_patterns: ["fp-003"],
    validator_tier: "tier_a",
    detection_logic: "Parse all convex/*.ts query functions. Identify tables marked as tenant-scoped (by convention or schema annotation). For each query on those tables, verify the filter chain includes orgId comparison. Report missing filters as critical.",
    false_positive_rate: 0.08,
  },
  {
    heuristic_id: "vh-003",
    name: "Detect forms without validation",
    description: "Scan form components for missing Zod or schema validation before mutation calls",
    target_failure_patterns: ["fp-006"],
    validator_tier: "tier_b",
    detection_logic: "Find all components with <form> or useForm(). Check if onSubmit path includes zodResolver, safeParse, or equivalent validation. Flag forms that call mutations with unvalidated data. Exclude search forms and simple filters.",
    false_positive_rate: 0.12,
  },
  {
    heuristic_id: "vh-004",
    name: "Detect missing empty states",
    description: "Scan list/table components for missing empty state handling",
    target_failure_patterns: ["fp-001"],
    validator_tier: "tier_b",
    detection_logic: "Find components that map over arrays or render table rows. Check if there is a conditional branch for empty/zero-length arrays that renders a meaningful empty state component. Flag components that would render nothing when data is empty.",
    false_positive_rate: 0.15,
  },
  {
    heuristic_id: "vh-005",
    name: "Detect unverified webhook handlers",
    description: "Scan webhook endpoints for missing signature verification",
    target_failure_patterns: ["fp-007"],
    validator_tier: "tier_a",
    detection_logic: "Find all files matching *webhook* or *hook* in API routes. Verify each imports and calls a signature verification function (stripe.webhooks.constructEvent, crypto.timingSafeEqual, etc.) before processing the request body. Report unverified handlers as critical.",
    false_positive_rate: 0.03,
  },
  {
    heuristic_id: "vh-006",
    name: "Detect missing loading states",
    description: "Scan components using data fetching hooks for missing loading state handling",
    target_failure_patterns: ["fp-008"],
    validator_tier: "tier_c",
    detection_logic: "Find components using useQuery, useSWR, useEffect with fetch, or similar data-fetching patterns. Check if the component handles the loading/pending state with a skeleton, spinner, or placeholder. Flag components that render nothing during loading.",
    false_positive_rate: 0.18,
  },
  {
    heuristic_id: "vh-007",
    name: "Detect destructive actions without confirmation",
    description: "Scan click handlers for delete/archive/remove actions missing confirmation dialogs",
    target_failure_patterns: ["fp-005"],
    validator_tier: "tier_b",
    detection_logic: "Find onClick/onPress handlers that call mutations with destructive names (delete, remove, archive, purge, destroy). Check if the handler first opens a confirmation dialog or modal. Flag direct mutation calls without confirmation step.",
    false_positive_rate: 0.10,
  },
  {
    heuristic_id: "vh-008",
    name: "Detect missing error transitions in state machines",
    description: "Scan XState machine definitions for invoke states without onError transitions",
    target_failure_patterns: ["fp-025"],
    validator_tier: "tier_b",
    detection_logic: "Parse XState createMachine/setup calls. For each state with an invoke property, check if onError is defined. For each state with an async service, verify error handling exists. Flag states where errors would cause the machine to freeze.",
    false_positive_rate: 0.07,
  },
  {
    heuristic_id: "vh-009",
    name: "Detect environment variable usage without validation",
    description: "Scan for process.env access without startup validation schema",
    target_failure_patterns: ["fp-020"],
    validator_tier: "tier_c",
    detection_logic: "Find all process.env.VARIABLE_NAME references across the codebase. Check if a centralized env validation schema (env.ts or similar) covers all referenced variables. Flag variables used at runtime but not included in the validation schema.",
    false_positive_rate: 0.14,
  },
  {
    heuristic_id: "vh-010",
    name: "Detect optimistic updates without rollback",
    description: "Scan mutation calls with optimistic updates for missing error rollback handlers",
    target_failure_patterns: ["fp-021"],
    validator_tier: "tier_b",
    detection_logic: "Find mutation calls that include optimisticUpdate or onMutate callbacks. Check if corresponding onError/onSettled callbacks restore previous state. Flag optimistic updates where the error path does not revert the UI change.",
    false_positive_rate: 0.11,
  },
];
