/**
 * Deployment Handler — pushes to GitHub and deploys to Vercel.
 *
 * This is the last node in the pipeline. After building and validation:
 * 1. Creates a GitHub repo and pushes the generated app
 * 2. Creates a Vercel project linked to the GitHub repo
 * 3. Triggers deployment and waits for it to be ready
 * 4. Returns a live URL in state.deploymentUrl
 *
 * If deployment services are not configured (no tokens), the handler
 * completes gracefully — the build is still successful, just not deployed.
 */

import type { AESStateType } from "../state.js";
import { getCallbacks } from "../graph.js";
import {
  GithubService,
  isGithubConfigured,
} from "../services/github-service.js";
import {
  VercelService,
  isVercelConfigured,
} from "../services/vercel-service.js";
import {
  deployToCloudflare,
  deployViaApi,
  type CloudflareDeployConfig,
} from "../deploy/cloudflare-deploy.js";

export async function deploymentHandler(
  state: AESStateType,
): Promise<Partial<AESStateType>> {
  const cb = getCallbacks();

  cb?.onGate("deploying", "Deploying application...");

  // Check if we have build results with a workspace
  const appBuild = state.buildResults?.["__app__"];
  if (!appBuild) {
    cb?.onFail("No app build result found — cannot deploy");
    return {
      currentGate: "failed" as any,
      errorMessage: "No app build result to deploy",
    };
  }

  // Derive app slug from AppSpec
  const appSlug = (state.appSpec?.title || "aes-app")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .substring(0, 50);

  const appDescription =
    state.appSpec?.summary ||
    `Generated by AES from: ${state.rawRequest}`;

  // ── Cloudflare Dynamic Workers deploy path ──
  if (state.deployTarget === "cloudflare") {
    const workspacePath = appBuild.workspace_path || appBuild.workspace?.path;
    if (!workspacePath) {
      cb?.onFail("No workspace path — cannot deploy to Cloudflare");
      return { currentGate: "failed" as any, errorMessage: "No workspace path for Cloudflare deploy" };
    }

    const cfGateway = process.env.AES_CF_GATEWAY_URL;
    const cfToken = process.env.AES_CF_API_TOKEN;
    const cfAccount = process.env.AES_CF_ACCOUNT_ID;

    if (!cfToken || !cfAccount) {
      cb?.onWarn("Cloudflare credentials not configured (AES_CF_API_TOKEN / AES_CF_ACCOUNT_ID). Falling back to local.");
    } else {
      cb?.onStep("Deploying to Cloudflare Dynamic Workers...");

      const cfConfig: CloudflareDeployConfig = {
        gatewayUrl: cfGateway || "",
        apiToken: cfToken,
        accountId: cfAccount,
        appName: appSlug,
        d1DatabaseId: process.env.AES_CF_D1_DATABASE_ID,
        kvNamespaceId: process.env.AES_CF_KV_NAMESPACE_ID,
        r2BucketName: process.env.AES_CF_R2_BUCKET,
      };

      // Use gateway if available, otherwise direct API
      const result = cfGateway
        ? await deployToCloudflare(workspacePath, cfConfig)
        : await deployViaApi(workspacePath, cfConfig);

      if (result.success) {
        cb?.onSuccess(`Deployed to Cloudflare: ${result.previewUrl} (${result.fileCount} files, ${Math.round(result.bundleSize / 1024)}KB)`);
        return {
          currentGate: "complete" as any,
          previewUrl: result.previewUrl,
          deploymentUrl: result.previewUrl,
        };
      } else {
        cb?.onWarn(`Cloudflare deploy failed: ${result.error}. Build complete but not deployed.`);
        return {
          currentGate: "complete" as any,
          errorMessage: `Cloudflare deploy failed: ${result.error}`,
        };
      }
    }
  }

  // ── Local / Vercel / GitHub deploy path ──
  const hasGithub = isGithubConfigured();
  const hasVercel = isVercelConfigured();

  if (!hasGithub && !hasVercel) {
    cb?.onWarn(
      "No deployment services configured (GITHUB_TOKEN / VERCEL_TOKEN). Build complete but not deployed.",
    );
    cb?.onSuccess(
      "Build complete. App ready in workspace but not deployed (set GITHUB_TOKEN and VERCEL_TOKEN to enable).",
    );
    return {
      currentGate: "complete" as any,
      // No deploymentUrl — services not configured
    };
  }

  let githubRepoUrl: string | null = null;
  let githubFullName: string | null = null;
  let deploymentUrl: string | null = null;

  // Phase 1: Push to GitHub
  if (hasGithub) {
    try {
      cb?.onStep("Creating GitHub repository...");
      const github = new GithubService();

      const repoName = `${appSlug}-${state.jobId.substring(0, 8)}`;
      const repo = await github.createRepo(
        repoName,
        appDescription,
        false,
      );

      githubRepoUrl = repo.html_url;
      githubFullName = repo.full_name;

      cb?.onStep("Pushing code to GitHub...");

      // The workspace path is stored in the build result by the builder-dispatcher
      const workspacePath =
        appBuild.workspace_path || appBuild.workspace?.path;

      if (workspacePath) {
        await github.pushWorkspace(workspacePath, repo.clone_url);
        cb?.onSuccess(`Code pushed to ${repo.html_url}`);
      } else {
        cb?.onWarn(
          "Workspace path not available in build result — cannot push to GitHub",
        );
      }
    } catch (err: any) {
      cb?.onWarn(`GitHub push failed: ${err.message}`);
      // Continue — we can still try to complete without deployment
    }
  }

  // Phase 2: Deploy to Vercel
  if (hasVercel && githubFullName) {
    try {
      cb?.onStep("Creating Vercel project...");
      const vercel = new VercelService();

      // Env vars for the deployed app
      const envVars: Record<string, string> = {};

      // Add Clerk keys if configured
      if (process.env.AES_CLERK_PUBLISHABLE_KEY) {
        envVars["NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"] =
          process.env.AES_CLERK_PUBLISHABLE_KEY;
      }
      if (process.env.AES_CLERK_SECRET_KEY) {
        envVars["CLERK_SECRET_KEY"] = process.env.AES_CLERK_SECRET_KEY;
      }
      // Add Convex URL if configured
      if (process.env.AES_CONVEX_URL) {
        envVars["NEXT_PUBLIC_CONVEX_URL"] = process.env.AES_CONVEX_URL;
      }

      const project = await vercel.createProject(
        appSlug,
        githubFullName,
        envVars,
      );

      cb?.onStep("Triggering deployment...");
      const deployment = await vercel.triggerDeployment(project.name);

      cb?.onStep("Waiting for deployment to be ready...");
      const result = await vercel.waitForDeployment(
        deployment.id,
        300000,
      ); // 5 min timeout

      deploymentUrl = result.url;
      cb?.onSuccess(`Deployed to ${deploymentUrl}`);
    } catch (err: any) {
      cb?.onWarn(`Vercel deployment failed: ${err.message}`);
      // Don't fail the pipeline — the build succeeded, deploy is best-effort
    }
  } else if (hasVercel && !githubFullName) {
    cb?.onWarn(
      "Vercel deployment requires GitHub — code must be pushed to a repo first",
    );
  }

  // Build summary
  const parts: string[] = [];
  if (githubRepoUrl) parts.push(`GitHub: ${githubRepoUrl}`);
  if (deploymentUrl) parts.push(`Live: ${deploymentUrl}`);
  if (parts.length === 0) parts.push("Build complete (no deployment configured)");

  cb?.onSuccess(parts.join(" | "));

  return {
    currentGate: "complete" as any,
    deploymentUrl,
  };
}
