export interface PRContext {
  title: string;
  body: string;
  branch: string;
  targetBranch: string;
  repo: string;
  bridgeId: string;
  featureId: string;
  labels: string[];
}

/**
 * Build the PR body from builder output.
 * Includes: bridge reference, scope summary, files changed, tests run, reuse assets used.
 */
export function buildPRBody(ctx: {
  bridgeId: string;
  featureId: string;
  featureName: string;
  objective: string;
  filesCreated: string[];
  filesModified: string[];
  reuseAssetsUsed: string[];
  testResults: { test_id: string; passed: boolean }[];
}): string {
  const testsSection = ctx.testResults
    .map((t) => `- ${t.passed ? "\u2705" : "\u274C"} ${t.test_id}`)
    .join("\n");

  const reuseSection = ctx.reuseAssetsUsed.length > 0
    ? ctx.reuseAssetsUsed.map((a) => `- ${a}`).join("\n")
    : "None \u2014 all new code";

  return [
    `## AES Build: ${ctx.featureName}`,
    "",
    `**Bridge:** \`${ctx.bridgeId}\``,
    `**Feature:** \`${ctx.featureId}\``,
    `**Objective:** ${ctx.objective}`,
    "",
    "### Files Created",
    ...ctx.filesCreated.map((f) => `- \`${f}\``),
    "",
    "### Files Modified",
    ...ctx.filesModified.map((f) => `- \`${f}\``),
    "",
    "### Reuse Assets Used",
    reuseSection,
    "",
    "### Test Results",
    testsSection,
    "",
    "---",
    "_Generated by AES v12 \u2014 Governed Software Factory_",
  ].join("\n");
}

/**
 * PR labels based on feature properties.
 */
export function getPRLabels(featureProperties: {
  priority: string;
  audit_required: boolean;
  has_destructive_actions: boolean;
}): string[] {
  const labels = ["aes-generated"];
  labels.push(`priority:${featureProperties.priority}`);
  if (featureProperties.audit_required) labels.push("audit-required");
  if (featureProperties.has_destructive_actions) labels.push("has-destructive-actions");
  return labels;
}
